### ISSUE TITLE
attach binary compiled app to github releases?

### ISSUE THREAD

**Issue by AlJohri** [vshatskyi/black-screen#934]
https://github.com/blog/1547-release-your-software

>You can also attach binary assets (such as compiled executables, minified scripts, documentation) to a release. Once published, the release details and assets are available to anyone that can view the repository.

**Comment by vshatskyi** [comment]
Aren't they already attached? https://github.com/vshatskyi/black-screen/releases

**Comment by AlJohri** [comment]
The compiled app or dmg? I don't see it; I can only download the source code. Do you have a direct link for the latest release?

**Comment by vshatskyi** [comment]
Nevermind, I'm stupid. I can see how it looks like in an anonymous tab. If you go to the second page, you'll see dmg files. New releases are broken (aren't marked as pre-release), that's why you can't see the links.

**Comment by vshatskyi** [comment]
If somebody wishes to fix it, here's the line. https://github.com/vshatskyi/black-screen/blob/master/housekeeping/deploy.sh#L24

**Comment by noygal** [comment]
@vshatskyi, I took a look and I can't figured whats wrong, also when checking the file [history](https://github.com/vshatskyi/black-screen/commits/master/housekeeping/deploy.sh) it hasn't been changed since Jul 10 and this issue start to pop up between 23 to 29 Nov (v0.2.93 to v0.2.94), so it might be unrelated.

I also found that this issue effect the brew cask installation, I can't install anything pass v0.2.93.
