### ISSUE TITLE
Treat whitespace a separate token in scanner/node in AST

### ISSUE THREAD

**Issue by drew-gross** [vshatskyi/black-screen#938]
Our scanner, like most, doesn't emit emit whitespace tokens. Whitespace matters to us when doing autocomplete, though, and I had to do a bunch of hacks in #933 to make it work. Adding whitespace tokens might make stuff cleaner. Thoughts @vshatskyi or anyone else?

**Comment by vshatskyi** [comment]
I think the usual approach is to have separate *parse tree* and *syntax tree*. What were the 

The core issue is that we need to deal with incorrect inputs. They're incorrect because they're being typed right now, so suddenly in `git add ` an empty WORD at the end is a valid token because that's what a person is going to type next. I know that the TS parser has the same issue and solves it in the same way - having "metainformation" on tokens.

**Comment by drew-gross** [comment]
So basically what he have. Maybe the best approach would be to stop eating trailing spaces, and have the scanner allow a `Word` to be whitespace with no characters after it, instead of making that an `Invalid`?

**Comment by vshatskyi** [comment]
According to POSIX shell specification it can't be empty, so this sounds hack-ish. http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html

We extend grammar to include known "in-progress" states. How about creating a base class `InvalidLeaf` and have `EmptyWord` inherit from it? This way we'll still be able to say if the command is valid when we need that.
